/* Generated by chris 2008/11/25 for mapping a code page number
 * to a canonical name used in YL_I18N. If new code page supported,
 * add the mapping to this file. CP950 is big5.
 */

/* chris: alias needed or not? */

MAP(950, "BIG5", cp950)
MAP(20127, "ASCII", ascii)
MAP(1200, "UCS2-LE", ucs2le)
MAP(65001, "UTF-8", utf8)
